name: Download CI artifact

on:
  workflow_call:
    inputs:
      runsOn:
        default: "ubuntu-latest"
        required: false
        type: string
      backend:
        description: "github or s3"
        default: "github"
        required: false
        type: string
      artifactName:
        default: ""
        required: false
        type: string
      artifactPattern:
        default: ""
        required: false
        type: string
      downloadPath:
        required: true
        type: string
      mergeMultiple:
        default: false
        required: false
        type: boolean
      s3RunPrefix:
        default: ""
        required: false
        type: string
      ciArtifactsS3BucketSecret:
        default: "CI_ARTIFACTS_S3_BUCKET"
        required: false
        type: string
      ciArtifactsAwsAccessKeyIDSecret:
        default: "CI_ARTIFACTS_AWS_KEY"
        required: false
        type: string
      ciArtifactsAwsSecretAccessKeySecret:
        default: "CI_ARTIFACTS_AWS_SECRET"
        required: false
        type: string
      ciArtifactsAwsRegionSecret:
        default: "CI_ARTIFACTS_S3_REGION"
        required: false
        type: string
      ciArtifactsAwsEndpointUrlSecret:
        default: "CI_ARTIFACTS_S3_ENDPOINT"
        required: false
        type: string

jobs:
  download:
    name: Download CI artifact
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Download
        uses: $/.github/actions/ci-artifacts-download
        with:
          backend: ${{ inputs.backend }}
          artifactName: ${{ inputs.artifactName }}
          artifactPattern: ${{ inputs.artifactPattern }}
          downloadPath: ${{ inputs.downloadPath }}
          mergeMultiple: ${{ inputs.mergeMultiple }}
          s3Bucket: ${{ secrets[inputs.ciArtifactsS3BucketSecret] }}
          s3RunPrefix: ${{ inputs.s3RunPrefix != '' && inputs.s3RunPrefix || format('{0}/{1}/', github.run_id, github.run_attempt) }}
          awsAccessKeyId: ${{ secrets[inputs.ciArtifactsAwsAccessKeyIDSecret] }}
          awsSecretAccessKey: ${{ secrets[inputs.ciArtifactsAwsSecretAccessKeySecret] }}
          awsRegion: ${{ secrets[inputs.ciArtifactsAwsRegionSecret] }}
          awsEndpointUrl: ${{ secrets[inputs.ciArtifactsAwsEndpointUrlSecret] }}
