name: Private Packagist Conductor

on:
  workflow_call:
    inputs:
      runsOn:
        description: Define on which runner this workflow should run
        default: "ubuntu-latest"
        required: false
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string

jobs:
  conductor:
    name: Private Packagist Conductor
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            ${{ inputs.workingDirectory }}composer.json
            ${{ inputs.workingDirectory }}composer.lock
      - name: Get desired PHP version
        id: supported-versions-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@b1da538007a030a09a7d257bd3881829a3544882 # v2.1.0
      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        env:
          fail-fast: true
        with:
          php-version: "${{ steps.supported-versions-matrix.outputs.lowest }}"
          coverage: "none"
          extensions: ${{ join(fromJson(steps.supported-versions-matrix.outputs.extensions), ',') }}
      - name: "Running Conductor"
        uses: packagist/conductor-github-action@3513567296cf906ee3c97ba63df6f6d7ddcc55a5 # 1.6.1
