name: Check Markdown links

on:
  workflow_call:
    inputs:
      runsOn:
        description: Define on which runner this workflow should run
        default: "ubuntu-latest"
        required: false
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string
      markdownLinkCheckSparseCheckout:
        description: Additional files/patterns for the sparse checkout
        default: ""
        required: false
        type: string

#defaults:
#  run:
#    working-directory: ${{ inputs.workingDirectory }}

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            !${{ inputs.workingDirectory }}/*
            ${{ inputs.workingDirectory }}/**/*.md
            ${{ inputs.markdownLinkCheckSparseCheckout }}
      - name: Check Markdown links
        uses: umbrelladocs/action-linkspector@036f295d12b67b0c4b445bc83db0538afb78db69 # v1.5.2
        with:
          reporter: github-pr-review
          fail_on_error: true
#          config_file: etc/ci/markdown-link-checker.json
