name: Package
on:
  workflow_call:
    inputs:
      initialTag:
        description: The tag to fallback to when no previous tag could be found.
        default: 1.0.0
        required: false
        type: string
      dependencyUpdaters:
        description: CSV list of bot AppId's that create PR's to updated dependencies like RenovateBot and DependaBot
        default: 49699333
        required: false
        type: string
      jsonPattern:
        description: The pattern to match which JSON files to check
        default: "\\.json$"
        required: false
        type: string
      requiredLabels:
        description: One of the labels to be set on PR
        default: "Bug 🐞,Dependencies 📦,Feature 🏗,Enhancement ✨"
        required: false
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string
      disableSetMilestone:
        description: Disable the setting of milestones
        default: false
        required: false
        type: boolean
      disableMarkdownLinkCheck:
        description: Disable the checking of links in markdown files
        default: false
        required: false
        type: boolean
      disableComposerLockDiff:
        description: Disable the diffing of composer lock files
        default: false
        required: false
        type: boolean
      disableRequiredLabels:
        description: Disable failing PR's when certain labels are missing
        default: false
        required: false
        type: boolean
jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
    with:
      jsonPattern: ${{ inputs.jsonPattern }}
      workingDirectory: ${{ inputs.workingDirectory }}
  set-milestone:
    name: Set Milestone
    if: inputs.disableSetMilestone == false
    uses: ./.github/workflows/package-set-milestone-on-pr.yaml
    with:
      initialTag: ${{ inputs.initialTag }}
      dependencyUpdaters: ${{ inputs.dependencyUpdaters }}
  markdown-link-check:
    name: Check Markdown links
    if: inputs.disableMarkdownLinkCheck == false
    uses: ./.github/workflows/markdown-check-links.yaml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}
  comment-composer-lock-diff:
    name: Composer Diff
    if: inputs.disableComposerLockDiff == false
    uses: ./.github/workflows/composer-diff.yaml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}
  required-labels:
    name: Required Labels
    if: inputs.disableRequiredLabels == false && github.event_name == 'pull_request'
    uses: ./.github/workflows/required-labels.yaml
    with:
      requiredLabels: ${{ inputs.requiredLabels }}
