name: Package
on:
  workflow_call:
    inputs:
      dependencyUpdaters:
        description: CSV list of bot AppId's that create PR's to updated dependencies like RenovateBot and DependaBot
        default: 49699333
        required: false
        type: string
      jsonPattern:
        description: The pattern to match which JSON files to check
        default: "\\.json$"
        required: false
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string
      disableMarkdownLinkCheck:
        description: Disable the checking of links in markdown files
        default: false
        required: false
        type: boolean
      disableComposerLockDiff:
        description: Disable the diffing of composer lock files
        default: false
        required: false
        type: boolean
      disableRequiredLabels:
        description: Disable failing PR's when certain labels are missing
        default: false
        required: false
        type: boolean
      services:
        description: Any additional services to use
        default: "{}"
        required: false
        type: string
      env:
        description: Any additional environment variables
        default: "{}"
        required: false
        type: string
jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
    with:
      jsonPattern: ${{ inputs.jsonPattern }}
      workingDirectory: ${{ inputs.workingDirectory }}
      services: ${{ inputs.services }}
      env: ${{ inputs.env }}
  markdown-link-check:
    name: Check Markdown links
    if: inputs.disableMarkdownLinkCheck == false
    uses: ./.github/workflows/markdown-check-links.yaml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}