name: Builds Assets Router
on:
  workflow_call:
    inputs:
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string
      applicationType:
        description: The type of project this is, release and deployment wise
        default: ""
        required: false
        type: string
      vitePressDirectory:
        description: The directory that container VitePress
        default: ""
        required: false
        type: string
      runsOn:
        description: Define on which runner to run workflows where order doesn't matter should run
        default: "ubuntu-latest"
        required: true
        type: string
      distBall:
        description: The path to the static files to be synced to S3
        default: "milestone-dist"
        required: true
        type: string
      commands:
        description: The commands to execute
        default: ""
        required: false
        type: string
      commandsOutputPath:
        description: Where to get to resulting files from the commands
        default: ""
        required: false
        type: string
jobs:
  vitepress:
    name: Deploy assets to CDN and invalidate caches
    if: ${{ inputs.applicationType == 'vitepress' || inputs.applicationType == 'vuepress' }}
    uses: ./.github/workflows/project-craft-release-cdn-build-vitepress.yaml
    secrets: inherit
    with:
      runsOn: ${{ inputs.runsOn }}
      distBall: ${{ inputs.distBall }}
      workingDirectory: ${{ inputs.workingDirectory }}
      vitePressDirectory: ${{ inputs.vitePressDirectory }}
      applicationType: ${{ inputs.applicationType }}
  commands:
    name: Deploy assets to CDN and invalidate caches
    if: ${{ inputs.applicationType == 'commands' }}
    uses: ./.github/workflows/project-craft-release-cdn-build-commands.yaml
    secrets: inherit
    with:
      runsOn: ${{ inputs.runsOn }}
      distBall: ${{ inputs.distBall }}
      workingDirectory: ${{ inputs.workingDirectory }}
      commands: ${{ inputs.commands }}
      commandsOutputPath: ${{ inputs.commandsOutputPath }}
