name: Deploy assets to CDN
on:
  workflow_call:
    inputs:
      milestone:
        description: The tag to deploy
        required: true
        type: string
      staticFilesPath:
        description: The path to the static files to be synced to S3
        default: "public"
        required: true
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string
      runsOn:
        description: Define on which runner to run workflows where order doesn't matter should run
        default: "ubuntu-latest"
        required: true
        type: string
      awsAccessKeyIDSecret:
        description: The secret name that holds the AWS access key ID
        default: "AWS_KEY"
        required: true
        type: string
      awsSecretAccessKeySecret:
        description: The secret name that holds the AWS access key secret
        default: "AWS_SECRET"
        required: true
        type: string
      awsRegionSecret:
        description: The secret name that holds the AWS region
        default: "AWS_REGION"
        required: true
        type: string
      awsEndpointUrlSecret:
        description: The secret name that holds the AWS endpoint URL
        default: "AWS_ENDPOINT_URL"
        required: false
        type: string
      cdnAwsS3BucketSecret:
        description: The secret name that holds the AWS S3 bucket name
        default: "CDN_HOSTED_S3_BUCKET"
        required: true
        type: string
      cdnAwsCloudFrontDistributionIDSecret:
        description: The secret name that holds the AWS cloudfront distribution id
        default: "CDN_HOSTED_DISTRIBUTION_ID"
        required: true
        type: string
jobs:
  build-assets:
    name: Zip up static assets for upload
    runs-on: ${{ inputs.runsOn }}
    env:
      awsEndpointUrlSecret: ${{ secrets[inputs.awsEndpointUrlSecret] }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            !${{ inputs.workingDirectory }}/*
            /${{ inputs.workingDirectory }}${{ inputs.staticFilesPath }}*
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.milestone }}-dist
          path: ${{ inputs.workingDirectory }}${{ inputs.staticFilesPath }}
  cdn-hosted-deploy:
    name: Deploy assets to CDN and invalidate caches
    needs:
      - build-assets
    uses: ./.github/workflows/s3-upload.yaml
    secrets: inherit
    with:
      runsOn: ${{ inputs.runsOn }}
      distBall: ${{ inputs.milestone }}-dist
      workingDirectory: ${{ inputs.workingDirectory }}
      awsAccessKeyIDSecret: ${{ inputs.awsAccessKeyIDSecret }}
      awsSecretAccessKeySecret: ${{ inputs.awsSecretAccessKeySecret }}
      awsRegionSecret: ${{ inputs.awsRegionSecret }}
      awsEndpointUrlSecret: ${{ inputs.awsEndpointUrlSecret }}
      cdnAwsS3BucketSecret: ${{ inputs.cdnAwsS3BucketSecret }}
      cdnAwsCloudFrontDistributionIDSecret: ${{ inputs.cdnAwsCloudFrontDistributionIDSecret }}
